In [39]:
import numpy as np
c = np.arange(9).reshape(3,3)
print(c)
d = []
for i in c:
    d.append(i[2])

# print(d)

d = np.array((d))

# print(d)

dd = d.reshape(3,1)
print(dd)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2]
 [5]
 [8]]


In [71]:
import tensorflow as tf

# 创建一个常量 op, 产生一个 1x2 矩阵. 这个 op 被作为一个节点
# 加到默认图中.
#
# 构造器的返回值代表该常量 op 的返回值.
matrix1 = tf.constant([[[2,3,4]]])

# matrix2 = matrix1[0,0,2]
matrix2 = tf.reshape(matrix1[0,0,2],(1,1,1))

print(matrix1.shape)
print(matrix2.shape)


(1, 1, 3)
(1, 1, 1)
